[tools]
pipx = "latest"
node = "lts"
lua-language-server = "latest"
stylua = "latest"
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"
prettier = "latest"
ruff = "latest"
black = "latest"
"npm:@openai/codex" = "latest"
"npm:bash-language-server" = "latest"
"npm:fish-lsp" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"pipx:basedpyright" = "latest"
"github:GDRETools/gdsdecomp" = "latest"
