- defaults:
    create:
      mode: 0755
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- create:
    ~/.ssh:
        mode: 0700

- link:
    ~/.ssh/config:
      force: true
      path: configs/ssh/config

    ~/.config/git/attributes: configs/git/attributes
    ~/.config/git/config: configs/git/config

    ~/.zshenv: configs/zsh/zshenv
    ~/.config/zsh/.zshrc: configs/zsh/zshrc
    ~/.config/zsh/.zsh_plugins.txt: configs/zsh/zsh_plugins.txt
    ~/.config/zsh/.zshrc.d/:
      glob: true
      path: configs/zsh/zshrc.d/**

    ~/.config/starship/config.toml: configs/starship/config.toml
