- defaults:
    create:
      mode: 0755
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- create:
    ~/.ssh:
      mode: 0700

- link:
    # Keyboard utils:
    ~/.config/kanata/config.kbd: configs/kanata/config.kbd

    # SSH:
    ~/.ssh/config:
      force: true
      path: configs/ssh/config

    # Git:
    ~/.config/git/attributes: configs/git/attributes
    ~/.config/git/config: configs/git/config

    # Shell:
    ~/.zshenv: configs/zsh/zshenv
    ~/.config/zsh/.zshrc: configs/zsh/zshrc
    ~/.config/zsh/.zsh_plugins.txt: configs/zsh/zsh_plugins.txt
    ~/.config/zsh/.zshrc.d/:
      glob: true
      path: configs/zsh/zshrc.d/**

    # Prompt:
    ~/.config/starship/config.toml: configs/starship/config.toml

    # Emulators:
    ~/.config/kitty/kitty.conf: configs/kitty/kitty.conf
    ~/.config/ghostty/config: configs/ghostty/config
    ~/.config/ghostty/shaders/:
      glob: true
      path: configs/ghostty/shaders/**.glsl

    # Editors:
    ~/.config/nano/nanorc: configs/nano/nanorc

    # ~/.config/vim/:
    #   glob: true
    #   path: configs/vim/**

    ~/.config/nvim/:
      glob: true
      path: configs/nvim/**

    # ~/.config/Code/User/settings.json: configs/vscode/settings.json
    # ~/.config/Code/User/keybindings.json: configs/vscode/keybindings.json

    ~/.config/zed/keymap.json: configs/zed/keymap.json
    ~/.config/zed/settings.json: configs/zed/settings.json
