- defaults:
    link:
      create: true
      relink: true

- clean: ["~", "~/.config"]

- link:
    ~/.zshenv: configs/zsh/zshenv
    ~/.config/zsh/.zshrc: configs/zsh/zshrc
    ~/.config/zsh/.zsh_plugins.txt: configs/zsh/zsh_plugins.txt
    ~/.config/zsh/.zshrc.d/:
      glob: true
      path: configs/zsh/zshrc.d/**
