config:
  create: true
  dotpath: auto

dotfiles:
  fish:
    src: fish
    dst: ~/.config/fish
    link: link_children

  nvim:
    src: nvim
    dst: ~/.config/nvim
    link: link_children

profiles:
  base:
    dotfiles:
      - fish
      - nvim
