#!/usr/bin/env bash

set -e

export SHELL="/bin/bash"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

ARGS="$@"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive


run_dotbot() {
    local config
    config = "$1"

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "$BASEDIR"
    -c "$config" $ARGS
}
