#!/usr/bin/env bash
# This script executes scenarios using the "dotbot" package.

set -euo pipefail

readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DOTBOT_DIR="dotbot"
readonly DOTBOT_BIN="bin/dotbot"
readonly ARGS=("$@")

run_dotbot() {
  local config
  config="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "$BASEDIR" \
    -c "$config" "${ARGS[@]}"
}

main() {
  cd "$BASEDIR"
  git submodule sync --quiet --recursive
  git submodule update --init --recursive

  run_dotbot ".install.conf.yml"
}


main
