#!/usr/bin/env bash
# This script executes dotbot scenarios described in the config files.

set -euo pipefail

readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DOTBOT_DIR="dotbot"
readonly DOTBOT_BIN="bin/dotbot"
readonly ARGS=("$@")

ask() {
  local question
  local response
  question="$1"
  read -r -p "${question} (y/N): " response

  case "$(echo "${response}" | tr '[:upper:]' '[:lower:]')" in
    y | yes | true | 1)
      return 0
      ;;
    *)
      return 1
  esac
}

run_dotbot() {
    local config
    config="$1"

    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
    -d "${BASEDIR}" \
    -c "${config}" "${ARGS[@]}"
}

main() {
  cd "${BASEDIR}"
  git submodule sync --quiet --recursive
  git submodule update --init --recursive

  if ask "Install packages?"; then
    run_dotbot "steps/packages.yml"
  fi

  if ask "Create symlinks to configurations?"; then
    run_dotbot "steps/configs.yml"
  fi

  if ask "Install flatpak apps?"; then
    run_dotbot "steps/flatpak.yml"
  fi
}


main
