$mainMod = SUPER

# $terminal = ...
# $launcher = ...
# $fileManager = ...
# $browser = ...
# $social = ...

$activeBorderColor = rgba(50,165,200,0.8)
$inactiveBorderColor = rgba(89,89,89,0.6)
$shadowColor = rgba(26,26,26,0.9)

# ----- Modules:
$modulesPath = ~/.config/hypr/modules

source = $modulesPath/monitors.conf
source = $modulesPath/input.conf
source = $modulesPath/misc.conf
source = $modulesPath/layout.conf
source = $modulesPath/rules.conf
source = $modulesPath/decorations.conf
source = $modulesPath/animations.conf
source = $modulesPath/autostart.conf
source = $modulesPath/keymap.conf
