# Any .zstyles if the file exist.
[[ ! -f "${ZDOTDIR:-$HOME}/.zstyles" ]] || source "${ZDOTDIR:-$HOME}/.zstyles"

# Custom vars.
source "${XDG_CONFIG_HOME:-$HOME}/.zshrc.d/exports.zsh"

# Plugin initialization (important: must come after the module with vars export).
source "${ZDOTDIR:-$HOME}/.zshrc.d/plugins.zsh"

# Custom aliases.
source "${XDG_CONFIG_HOME:-$HOME}/.zshrc.d/aliases.zsh"
