exec-once = uwsm-app -- /usr/lib/soteria-polkit/soteria
exec-once = uwsm-app -- swayosd-server
# exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- awww-daemon

exec-once = uwsm-app -- walker --gapplication-service
# exec-once = uwsm-app -- nwg-dock-hyprland -nolauncher -x -a center -p bottom -mb 5

exec-once = uwsm-app -- /usr/bin/hyprland-per-window-layout

# exec-once = uwsm app -- sleep 3 && flatpak run org.qbittorrent.qBittorrent
