decoration {
  rounding = 0
  rounding_power = 2

  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
    enabled = true
    special = true

    size = 8
    passes = 2
    noise = 0.05
    brightness = 0.60
    contrast = 0.75
    vibrancy = 0.1696

    brightness = 1.0
    contrast = 1.1
    vibrancy = 0.3
    vibrancy_darkness = 0.6
  }

  shadow {
    enabled = true
    ignore_window = true

    range = 4
    render_power = 2
    color = $shadowColor
  }
}
