cursor {
  hide_on_key_press =true
}

xwayland {
  force_zero_scaling = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  focus_on_activate = true
  on_focus_under_fullscreen = 1
  anr_missed_pings = 3
}
