# See https://raw.githubusercontent.com/abenz1267/walker/refs/heads/master/resources/config.toml

theme = "default"

force_keyboard_focus = true # forces keybaord focus to stay in `walker`

[keybinds]
next = ["Down", "ctrl j"]
previous = ["Up", "ctrl k"]
quick_activate = ["F1", "F2", "F3", "F4", "F5"]

[[providers.prefixes]]
prefix = "+"
provider = "menus:wallpapers"

[[providers.prefixes]]
prefix = "-"
provider = "menus:fonts"

[providers.actions]
"menus:wallpapers" = [
  { action = "set", label = "set", default = true, bind = "Return", after = "Nothing" },
  { action = "open_dir", label = "open in file manager", bind = "ctrl Return", after = "Close" },
  { action = "copy", label = "copy", bind = "ctrl c", after = "Close" },
]

[provired.actions]
"manus:fonts" = [
  { action = "menus:default", label = "copy", default = true, bind = "Return", after = "Close" },
]
