general {
  fail_timeout = 1000
  ignore_empty_input = true

  hide_cursor = true
}

background {
  monitor =
  path = screenshot

  blur_size = 4
  blur_passes = 3

  brightness = 0.5
  contrast = 0.75
  noise = 0.05
  vibrancy = 0.1
  vibrancy_darkness = 0.6
}

input-field {
  size = 20%, 7.5%

  inner_color = rgb(000000)

  rounding = 0
  outline_thickness = 2

  outer_color = rgb(000000)
  check_color = rgba(152, 195, 121, 0.5)
  fail_color = rgba(243, 139, 168, 0.5)
  capslock_color = rgba(201, 176, 62, 0.5)

  shadow_size = 4
  shadow_passes = 2
  shadow_color = rgba(0, 0, 0, 0.8)

  font_family = sans-serif
  font_color = rgb(ffffff)

  placeholder_text = Enter Password
  fail_text = $FAIL ($ATTEMPTS)

  fade_on_empty = false
}

animations {
  enabled = true
  animation = fadeIn, 1, 1, linear
  animation = fadeOut, 0
  animation = inputField, 1, 1, linear
}

auth {
  fingerprint:enabled = false
}
