[lockscreen]
fingerprint = false

[lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
type = "login_box"
output = "DP-1"

box_width = 720.0
box_height = 128.0

cx = 1720.0
cy = 768.0

[lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
center_password_text = true

show_unlock_hint = true
show_caps_lock = true

show_media = false
show_weather = false
show_keyboard_layout = false
show_login_button = false
show_session_buttons = false
