set nocompatible " not vi compatible.

packadd! editorconfig

syntax on
" set showmatch " show matching braces when text indicator is over them.

filetype plugin indent on " enable file type detection.
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent

set fixendofline
set nojoinspaces " suppress inserting two spaces between sentences.

set shortmess+=I " disable startup message.
set number
set relativenumber
set laststatus=2

set linebreak
set listchars=tab:>>,nbsp:~ " set list to see tabs and non-breakable spaces.
set nofoldenable

set wildmode=longest,list
set wildmenu

set incsearch " incremental search (as string is being typed).
set hlsearch " highlight search.
set ignorecase
set smartcase

set mouse+=a " enable mouse mode (scrolling, selection, etc).
set clipboard=unnamedplus
set noswapfile
set history=8192
set scrolloff=10 " show lines above and below cursor (when possible).

set backspace=indent,eol,start

command -nargs=0 Sudow w !sudo tee % >/dev/null

inoremap jj <Esc>

nnoremap <Tab> gt
nnoremap <S-Tab> gT

nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

nmap Q <Nop>

" Изменение формы курсора в зависимости от режима
" Change cursor shape depending on the mode.
let &t_SI = "\<Esc>[6 q" " vertical line for insert mode.
let &t_EI = "\<Esc>[2 q" " block for normal mode.
